version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '8080:80'
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
  app1:
    image: node-app
    environment: 
      - APPID=1111
  app2:
    image: node-app
    environment: 
      - APPID=2222
  app3:
    image: node-app
    environment: 
      - APPID=3333
  app4:
    image: node-app
    environment: 
      - APPID=4444
  app5:
    image: node-app
    environment: 
      - APPID=5555
    